name: Publish to Pypi

on:
  push:
    tags:
      - '*.*.*'

jobs:

  publish:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          pip install build twine "importlib_metadata<8"
          pip install -r requirements.txt
          npm install

      - name: Build and Publish package
        run: |
          npm run build
          python3 -m build
          twine upload dist/* -u __token__ -p ${{secrets.PYPI_TOKEN}} --non-interactive
